"""Scientific identifiers fixed by the approved project documents."""

PRODUCT_ID = "GLOBAL_MULTIYEAR_PHY_001_030"
DAILY_DATASET_ID = "cmems_mod_glo_phy_my_0.083deg_P1D-m"
MONTHLY_DATASET_ID = "cmems_mod_glo_phy_my_0.083deg_P1M-m"
CURRENT_VARIABLES = ("uo", "vo")
CURRENT_UNITS = "m s-1"
ANALYSIS_DEPTH_M = 0.494025
DEPTH_TOLERANCE_M = 1e-6
PROJECT_PERIOD_START = "2015-01-01"
PROJECT_PERIOD_END_EXCLUSIVE = "2026-01-01"
JFM_DAILY_COUNT = 993
MONTHLY_COUNT = 132
DISPLAY_TIMEZONE = "Asia/Jayapura"
